# Generated by Django 4.1.1 on 2022-12-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spapp', '0005_alter_post_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_quote', models.FileField(blank=True, null=True, upload_to='top-quote/')),
                ('bottom_quote', models.FileField(blank=True, null=True, upload_to='bottom-quote/')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.AddField(
            model_name='album',
            name='about_bottom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='album',
            name='about_middle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='album',
            name='about_quote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='album',
            name='about_top',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='album',
            name='bottom_quote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='album',
            name='contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='album',
            name='crousel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='album',
            name='head',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='album',
            name='reach_us',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='album',
            name='testimonials',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='album',
            name='top_quote',
            field=models.BooleanField(default=False),
        ),
    ]
