# Generated by Django 4.1.1 on 2022-12-16 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spapp', '0006_feature_remove_user_city_remove_user_country_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
