# Generated by Django 4.1.1 on 2022-12-16 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spapp', '0007_delete_feature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='testimonials',
            new_name='testimonial',
        ),
    ]
